
echo "True Zero Shot"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --no_rag --n_hops 1 --output_directory "./data/1hop_tzs"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --no_rag --n_hops 2 --output_directory "./data/2hop_tzs"

echo "Few Shot, n=0"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 0 --n_hops 1 --output_directory "./data/1hop_fn_0"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 0 --n_hops 2 --output_directory "./data/2hop_fn_0"

echo "Few Shot, n=2"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 2 --n_hops 1 --output_directory "./data/1hop_fn_2"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 2 --n_hops 2 --output_directory "./data/2hop_fn_2"
echo "Few Shot, n=4"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 4 --n_hops 1 --output_directory "./data/1hop_fn_4"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 4 --n_hops 2 --output_directory "./data/2hop_fn_4"
echo "Few shot, n=8"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 8 --n_hops 1 --output_directory "./data/1hop_fn_8"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 8 --n_hops 2 --output_directory "./data/2hop_fn_8"

echo "Zero Shot, n=0"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 0 --zero_shot --n_hops 1 --output_directory "./data/1hop_zn_0"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 0 --zero_shot --n_hops 2 --output_directory "./data/2hop_zn_0"
echo "Zero Shot, n=2"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 2 --zero_shot --n_hops 1 --output_directory "./data/1hop_zn_2"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 2 --zero_shot --n_hops 2 --output_directory "./data/2hop_zn_2"
echo "Zero Shot, n=4"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 4 --zero_shot --n_hops 1 --output_directory "./data/1hop_zn_4"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 4 --zero_shot --n_hops 2 --output_directory "./data/2hop_zn_4"
echo "Zero shot, n=8"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 8 --zero_shot --n_hops 1 --output_directory "./data/1hop_zn_8"
CUDA_VISIBLE_DEVICES="0,1" python gen_answer_with_pn_sets.py --n_negative 8 --zero_shot --n_hops 2 --output_directory "./data/2hop_zn_8"
